### ISSUE TITLE
CI to RELEASE on merge to `main`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#52]
The objective is to quickly ship updates with different version numbers to the GitHub Marketplace.

This is awesome to automatically handle semver updates based on conventional commits. 
https://github.com/ietf-tools/semver-action#example-workflow

**Comment by rndquu** [comment]
may I take this one?

this is a good start to prepare "architecture docs" as discussed with 0xcodercrane

**Comment by sergfeldman** [comment]
> may I take this one?
> 
> this is a good start to prepare "architecture docs" as discussed with 0xcodercrane

@rndquu In my opinion yes.
@pavlovcik would you mind?

**Comment by pavlovcik** [comment]
> @rndquu The time limit for this bounty is on 1/14/2023

lol savage. You can get a week!

@0xcodercrane I think we should make the minimum time 1 week because there could be situations where, for example, a bounty master working on the weekend assigns a one day bounty to a hunter and they don't check GitHub til the week starts.

**Comment by 0xcodercrane** [comment]
> may I take this one?
> 
> this is a good start to prepare "architecture docs" as discussed with 0xcodercrane

I agree

**Comment by 0xcodercrane** [comment]
ok. we also need to update weight value then.

**Comment by 0xcodercrane** [comment]
oh sorry @rndquu. I was testing the bounty bot. it unassigned you automatically lol

**Comment by 0xcodercrane** [comment]
Oh lol. local bot and production bot works together.

**Comment by pavlovcik** [comment]
> Oh lol. local bot and production bot works together.

Co-op campaign

**Comment by 0xcodercrane** [comment]
This issue will be tracked in https://github.com/ubiquity/bounty-bot/pull/88

**Comment by rndquu** [comment]
> This issue will be tracked in #88

I'm working on this issue right now. Should I continue working on it?

**Comment by pavlovcik** [comment]
> > This issue will be tracked in #88
> 
> I'm working on this issue right now. Should I continue working on it?

You ran out of time lol

I finished it

https://github.com/ubiquity/bounty-bot/pull/84

**Comment by 0xcodercrane** [comment]
oh I just thought the active PR is just @pavlovcik was working on. but I guess it doesn't also include automatic release action to github marketplace.

**Comment by pavlovcik** [comment]
> oh I just thought the active PR is just @pavlovcik was working on. but I guess it doesn't also include automatic release action to github marketplace.

Actually you're correct. My PR doesn't do anything marketplace related!

**Comment by 0xcodercrane** [comment]
hehe

**Comment by pavlovcik** [comment]
I can send the cash if you put your address here!

**Comment by 0xcodercrane** [comment]
> I can send the cash if you put your address here!

0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by pavlovcik** [comment]
Hey sorry I wasn't paying close attention to this issue but from what I understand this does not currently publish to the marketplace which means that this issue is not complete.

I asked ChatGPT and it says:

> In this example, the workflow is triggered when changes are pushed to the main branch. The workflow then checks out the code, sets up Node.js, installs the dependencies, and runs a publish-to-marketplace script. The publish-to-marketplace script should be customized to publish your GitHub Marketplace listing, and should make use of the GITHUB_TOKEN environment variable provided by GitHub Actions to authenticate with the GitHub API.

```yml
name: Publish to GitHub Marketplace

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Publish to GitHub Marketplace
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn deploy:marketplace
```
