### ISSUE TITLE
Remove a step to Get GitHub App token from marketplace.yml

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#93]
[marketplace.yml](https://github.com/ubiquity/bounty-bot/blob/development/.github/workflows/marketplace.yml) is kind of an example how to integrate bounty-bot app into their organization/repo. 

[Get GitHub App token](https://github.com/ubiquity/bounty-bot/blob/development/.github/workflows/marketplace.yml#L17) is used to get the github token. But if we add `GITHUB_TOKEN` directly to the `secrets`, we can definitely remove above and just update like the followings.

```
jobs:
  calculate_bounty_job:
    # ignore events invoked by bots
    if: >-
      github.event.pull_request.payload.sender.type != 'Bot'
    runs-on: ubuntu-latest
    name: Calculate Bounty with UbiquiBot
    steps:
      - name: Ubiquity Bounty Bot
        uses: ubiquity/bounty-bot@@v0.0.1-beta
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
