### ISSUE TITLE
Weekly Update Report Configuration

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#98]
There exists a similar task https://github.com/ubiquity/bounty-bot/issues/45, but it requires advanced statistics to be collected. Current task describes a simple solution and later we can procede with https://github.com/ubiquity/bounty-bot/issues/45.

The bot should be able to generate a report of resolved issues for the previous week. The report should be posted to a Telegram group.

What should be done:
1. Add parameters `weekly_report_enabled`, `weekly_report_telegram_group` to the github action config. Example: 
```
- name: Ubiquity Bounty Bot
  uses: ubiquity/bounty-bot@v0.0.1
  with: 
    weekly_report_enabled: true
    weekly_report_telegram_group: UbiquityDevPool
```

By default `weekly_report_enabled` should be disabled.

2. Every Monday generate weekly report from issues that were resolved during the previous week and post the report to Telegram group. If there were no resolved issues then do not post anything.

Example:
```
Weekly update of resolved issues

- Default Label Colors
- Telegram bot account
- Telegram Bot Adapter
```

3. Update `README.md` with bot config docs.
