### ISSUE TITLE
Implement stale issues report

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#99]
Every Monday the bot should generate a report for stale issues and post the report to Telegram group

What should be done:
1. Add parameter `stale_issues_report_enabled`, `stale_issues_report_telegram_group` to the github action config. Example:
```
- name: Ubiquity Bounty Bot
  uses: ubiquity/bounty-bot@v0.0.1
  with: 
    stale_issues_report_enabled: true
    stale_issues_report_telegram_group: UbiquityDevPool
```

By default `stale_issues_report_enabled` should be disabled.

2. Every Moday find all issues that have not been resolved for at least 7 days since their creation, generate a report from them and post to Telegram group. If there were no unresolved issues then do not post anything.

Issue info that should be posted:
- title
- URL
- price

Example:
```
Check our latest stale issues

Twitter Bot Account
https://github.com/ubiquity/bounty-bot/issues/56
Pice: 100 USD

CI to RELEASE on merge to main
https://github.com/ubiquity/bounty-bot/issues/52
Price: 100 USD
```

3. Update `README.md` with bot config docs.
